# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017-2022 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/hi6250/setup-makefiles.sh

#    vendor/huawei/hi6250/proprietary/vendor/lib/libhwui.so:system/lib/libhwui.so \
#    vendor/huawei/hi6250/proprietary/vendor/lib64/libhwui.so:system/lib64/libhwui.so \

PRODUCT_COPY_FILES += \
#    vendor/huawei/hi6250/proprietary/lib/libhwui.so:system/lib/libhwui.so \
#    vendor/huawei/hi6250/proprietary/lib64/libhwui.so:system/lib64/libhwui.so \
    vendor/huawei/hi6250/proprietary/vendor/etc/bluetooth/bt_vendor.conf:system/vendor/etc/bluetooth/bt_vendor.conf \
    vendor/huawei/hi6250/proprietary/vendor/etc/bluetooth/bt_vendor.conf:system/vendor/etc/bluetooth/bt_vendor.conf \
    vendor/huawei/hi6250/proprietary/vendor/etc/factory_modem.cfg:system/vendor/etc/factory_modem.cfg \
    vendor/huawei/hi6250/proprietary/vendor/etc/geoloc.conf:system/vendor/etc/geoloc.conf \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/config/gnss_lss_config_thirdparty.bin:system/vendor/etc/gnss/config/gnss_lss_config_thirdparty.bin \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/config/gnss_lss_rfg_key_thirdparty.pem:system/vendor/etc/gnss/config/gnss_lss_rfg_key_thirdparty.pem \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/config/gnss_lss_slp_thirdparty.p12:system/vendor/etc/gnss/config/gnss_lss_slp_thirdparty.p12 \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/config/gnss_suplconfig_hisi.xml:system/vendor/etc/gnss/config/gnss_suplconfig_hisi.xml \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/gnss_lss_thirdparty.conf:system/vendor/etc/gnss/gnss_lss_thirdparty.conf \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/c/a_1:system/vendor/etc/gnss/rmd/c/a_1 \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/c/aindex.bin:system/vendor/etc/gnss/rmd/c/aindex.bin \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/e/a_1:system/vendor/etc/gnss/rmd/e/a_1 \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/e/aindex.bin:system/vendor/etc/gnss/rmd/e/aindex.bin \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/f/a_1:system/vendor/etc/gnss/rmd/f/a_1 \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/f/aindex.bin:system/vendor/etc/gnss/rmd/f/aindex.bin \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/g/a_1:system/vendor/etc/gnss/rmd/g/a_1 \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/g/aindex.bin:system/vendor/etc/gnss/rmd/g/aindex.bin \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/t/a_1:system/vendor/etc/gnss/rmd/t/a_1 \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/rmd/t/aindex.bin:system/vendor/etc/gnss/rmd/t/aindex.bin \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/security/gnss_entel_hisi.bks:system/vendor/etc/gnss/security/gnss_entel_hisi.bks \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/security/gnss_iusacell_hisi.bks:system/vendor/etc/gnss/security/gnss_iusacell_hisi.bks \
    vendor/huawei/hi6250/proprietary/vendor/etc/gnss/security/gnss_vodafone_hisi.bks:system/vendor/etc/gnss/security/gnss_vodafone_hisi.bks \
    vendor/huawei/hi6250/proprietary/vendor/etc/media_codecs.xml:system/vendor/etc/media_codecs.xml \
    vendor/huawei/hi6250/proprietary/vendor/etc/media_codecs_performance.xml:system/vendor/etc/media_codecs_performance.xml \
    vendor/huawei/hi6250/proprietary/vendor/etc/modemConfig/balong/FieldTest.cfg:system/vendor/etc/modemConfig/balong/FieldTest.cfg \
    vendor/huawei/hi6250/proprietary/vendor/etc/modemConfig/balong/basic_name:system/vendor/etc/modemConfig/balong/basic_name \
    vendor/huawei/hi6250/proprietary/vendor/etc/modemConfig/hids_ue_msg.cfg:system/vendor/etc/modemConfig/hids_ue_msg.cfg \
    vendor/huawei/hi6250/proprietary/vendor/firmware/BCM4345C0_003.001.025.0033.0000_Generic.hcd:system/vendor/firmware/BCM4345C0_003.001.025.0033.0000_Generic.hcd \
    vendor/huawei/hi6250/proprietary/vendor/firmware/Total.wdk:system/vendor/firmware/Total.wdk \
    vendor/huawei/hi6250/proprietary/vendor/firmware/fw_bcm4334_hw_2ant.bin:system/vendor/firmware/fw_bcm4334_hw_2ant.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/fw_bcm4334_test_2ant.bin:system/vendor/firmware/fw_bcm4334_test_2ant.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/fw_bcm43455_apsta_hw.bin:system/vendor/firmware/fw_bcm43455_apsta_hw.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/fw_bcm43455_hw.bin:system/vendor/firmware/fw_bcm43455_hw.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/fw_bcm43455_test_hw_apsta.bin:system/vendor/firmware/fw_bcm43455_test_hw_apsta.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/hifi_6402.img:system/vendor/firmware/hifi_6402.img \
    vendor/huawei/hi6250/proprietary/vendor/firmware/hifi_6402_2spk.img:system/vendor/firmware/hifi_6402_2spk.img \
    vendor/huawei/hi6250/proprietary/vendor/firmware/isp_bw.elf:system/vendor/firmware/isp_bw.elf \
    vendor/huawei/hi6250/proprietary/vendor/firmware/isp_dts.img:system/vendor/firmware/isp_dts.img \
    vendor/huawei/hi6250/proprietary/vendor/firmware/isp_fw.elf:system/vendor/firmware/isp_fw.elf \
    vendor/huawei/hi6250/proprietary/vendor/firmware/nvram43455_hw.txt:system/vendor/firmware/nvram43455_hw.txt \
    vendor/huawei/hi6250/proprietary/vendor/firmware/nvram43455_hw_vn1.txt:system/vendor/firmware/nvram43455_hw_vn1.txt \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/Nemo_CS445A_default.bin:system/vendor/firmware/ts/Nemo_CS445A_default.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/Nemo_CS445A_junda.bin:system/vendor/firmware/ts/Nemo_CS445A_junda.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_auo_ili9885.bin:system/vendor/firmware/ts/berlin_auo_ili9885.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_auo_nt35532.bin:system/vendor/firmware/ts/berlin_auo_nt35532.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_boe_nt35532.bin:system/vendor/firmware/ts/berlin_boe_nt35532.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_boe_nt35532_lens.bin:system/vendor/firmware/ts/berlin_boe_nt35532_lens.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_inx_nt35532.bin:system/vendor/firmware/ts/berlin_inx_nt35532.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_inx_nt35532_lens.bin:system/vendor/firmware/ts/berlin_inx_nt35532_lens.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_tm_nt35596.bin:system/vendor/firmware/ts/berlin_tm_nt35596.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_tm_nt35596_lens.bin:system/vendor/firmware/ts/berlin_tm_nt35596_lens.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_tm_otm1901a.bin:system/vendor/firmware/ts/berlin_tm_otm1901a.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_tm_r63350.bin:system/vendor/firmware/ts/berlin_tm_r63350.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/berlin_tm_r63350_lens.bin:system/vendor/firmware/ts/berlin_tm_r63350_lens.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/prague_CYTT21403_default.bin:system/vendor/firmware/ts/prague_CYTT21403_default.bin \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/venus_synaptics_VENS11080_jdi.img:system/vendor/firmware/ts/venus_synaptics_VENS11080_jdi.img \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/venus_synaptics_VENS11120_cmi.img:system/vendor/firmware/ts/venus_synaptics_VENS11120_cmi.img \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/venus_synaptics_VENS11130_boe.img:system/vendor/firmware/ts/venus_synaptics_VENS11130_boe.img \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/venus_synaptics_VENS11140_ebbg.img:system/vendor/firmware/ts/venus_synaptics_VENS11140_ebbg.img \
    vendor/huawei/hi6250/proprietary/vendor/firmware/ts/venus_synaptics_VENS18100_lg.img:system/vendor/firmware/ts/venus_synaptics_VENS18100_lg.img \
    vendor/huawei/hi6250/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hw/camera.hi6250.so:system/vendor/lib/hw/camera.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hw/fm.bcm.hi6250.so:system/vendor/lib/hw/fm.bcm.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hw/fm.hisi.hi6250.so:system/vendor/lib/hw/fm.hisi.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hw/gatekeeper.hi6250.so:system/vendor/lib/hw/gatekeeper.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hw/gralloc.hi6250.so:system/vendor/lib/hw/gralloc.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hw/hwcomposer.hi6250.so:system/vendor/lib/hw/hwcomposer.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hw/keystore.hi6250.so:system/vendor/lib/hw/keystore.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hw/memtrack.hi6250.so:system/vendor/lib/hw/memtrack.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/hwcam/hwcam.ddt.so:system/vendor/lib/hwcam/hwcam.ddt.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libHWCamCfgSvr.so:system/vendor/lib/libHWCamCfgSvr.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libOpenCLFoundation.so:system/vendor/lib/libOpenCLFoundation.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libSR_opencl.so:system/vendor/lib/libSR_opencl.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/lib_device_interface.so:system/vendor/lib/lib_device_interface.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/lib_factory_interface.so:system/vendor/lib/lib_factory_interface.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/lib_wifi_sar.so:system/vendor/lib/lib_wifi_sar.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libasd.so:system/vendor/lib/libasd.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libaudio_custom.so:system/vendor/lib/libaudio_custom.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libbalong-ril-1.so:system/vendor/lib/libbalong-ril-1.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libbalong-ril-2.so:system/vendor/lib/libbalong-ril-2.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libbalong-ril.so:system/vendor/lib/libbalong-ril.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libc_sec_hisi_connectivity.so:system/vendor/lib/libc_sec_hisi_connectivity.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libc_secshared.so:system/vendor/lib/libc_secshared.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libchrlog.so:system/vendor/lib/libchrlog.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libconn_factory_test.so:system/vendor/lib/libconn_factory_test.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libfm_interface.so:system/vendor/lib/libfm_interface.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libhiion.so:system/vendor/lib/libhiion.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libhilog.so:system/vendor/lib/libhilog.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libhisi_efuse.so:system/vendor/lib/libhisi_efuse.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libhw_display_test.so:system/vendor/lib/libhw_display_test.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libhwlog.so:system/vendor/lib/libhwlog.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libimonitor.so:system/vendor/lib/libimonitor.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libmax98925.so:system/vendor/lib/libmax98925.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libnvme.so:system/vendor/lib/libnvme.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/liboeminfo.so:system/vendor/lib/liboeminfo.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libomx_vxd.so:system/vendor/lib/libomx_vxd.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libomx_vxe.so:system/vendor/lib/libomx_vxe.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libpf_customize_hisi.so:system/vendor/lib/libpf_customize_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libpf_oneimage_hisi.so:system/vendor/lib/libpf_oneimage_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libpf_rotate_hisi.so:system/vendor/lib/libpf_rotate_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libstagefrighthw.so:system/vendor/lib/libstagefrighthw.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libtas2560.so:system/vendor/lib/libtas2560.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libteec.so:system/vendor/lib/libteec.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/libtfa9895.so:system/vendor/lib/libtfa9895.so \
    vendor/huawei/hi6250/proprietary/vendor/lib/soundfx/liboffloadvisualizer.so:system/vendor/lib/soundfx/liboffloadvisualizer.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib64/egl/libGLES_mali.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hw/camera.hi6250.so:system/vendor/lib64/hw/camera.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hw/fm.bcm.hi6250.so:system/vendor/lib64/hw/fm.bcm.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hw/fm.hisi.hi6250.so:system/vendor/lib64/hw/fm.hisi.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hw/gatekeeper.hi6250.so:system/vendor/lib64/hw/gatekeeper.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hw/gralloc.hi6250.so:system/vendor/lib64/hw/gralloc.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hw/hwcomposer.hi6250.so:system/vendor/lib64/hw/hwcomposer.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hw/keystore.hi6250.so:system/vendor/lib64/hw/keystore.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hw/memtrack.hi6250.so:system/vendor/lib64/hw/memtrack.hi6250.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/hwcam/hwcam.ddt.so:system/vendor/lib64/hwcam/hwcam.ddt.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libHWCamCfgSvr.so:system/vendor/lib64/libHWCamCfgSvr.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libOpenCLFoundation.so:system/vendor/lib64/libOpenCLFoundation.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libSR_opencl.so:system/vendor/lib64/libSR_opencl.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/lib_device_interface.so:system/vendor/lib64/lib_device_interface.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/lib_factory_interface.so:system/vendor/lib64/lib_factory_interface.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/lib_mmi_interface.so:system/vendor/lib64/lib_mmi_interface.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/lib_wifi_sar.so:system/vendor/lib64/lib_wifi_sar.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libasd.so:system/vendor/lib64/libasd.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libaudio_custom.so:system/vendor/lib64/libaudio_custom.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libbalong-ril-1.so:system/vendor/lib64/libbalong-ril-1.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libbalong-ril-2.so:system/vendor/lib64/libbalong-ril-2.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libbalong-ril.so:system/vendor/lib64/libbalong-ril.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libc_sec_hisi_connectivity.so:system/vendor/lib64/libc_sec_hisi_connectivity.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libc_secshared.so:system/vendor/lib64/libc_secshared.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libchrlog.so:system/vendor/lib64/libchrlog.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libconn_factory_test.so:system/vendor/lib64/libconn_factory_test.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libdevice_status_api.so:system/vendor/lib64/libdevice_status_api.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libfm_interface.so:system/vendor/lib64/libfm_interface.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libgnss_common_hisi.so:system/vendor/lib64/libgnss_common_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libgnss_lss_gw_thirdparty.so:system/vendor/lib64/libgnss_lss_gw_thirdparty.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libgnss_supl10client_hisi.so:system/vendor/lib64/libgnss_supl10client_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libgnss_supl20client_hisi.so:system/vendor/lib64/libgnss_supl20client_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libgnss_supl20common_hisi.so:system/vendor/lib64/libgnss_supl20common_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libgnss_supl20if_hisi.so:system/vendor/lib64/libgnss_supl20if_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libhiion.so:system/vendor/lib64/libhiion.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libhilog.so:system/vendor/lib64/libhilog.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libhisi_efuse.so:system/vendor/lib64/libhisi_efuse.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libhw_display_test.so:system/vendor/lib64/libhw_display_test.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libhwlog.so:system/vendor/lib64/libhwlog.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libimonitor.so:system/vendor/lib64/libimonitor.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libmax98925.so:system/vendor/lib64/libmax98925.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libnvme.so:system/vendor/lib64/libnvme.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/liboeminfo.so:system/vendor/lib64/liboeminfo.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libomx_vxd.so:system/vendor/lib64/libomx_vxd.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libomx_vxe.so:system/vendor/lib64/libomx_vxe.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libpf_customize_hisi.so:system/vendor/lib64/libpf_customize_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libpf_oneimage_hisi.so:system/vendor/lib64/libpf_oneimage_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libpf_rotate_hisi.so:system/vendor/lib64/libpf_rotate_hisi.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libstagefrighthw.so:system/vendor/lib64/libstagefrighthw.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libtas2560.so:system/vendor/lib64/libtas2560.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libteec.so:system/vendor/lib64/libteec.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/libtfa9895.so:system/vendor/lib64/libtfa9895.so \
    vendor/huawei/hi6250/proprietary/vendor/lib64/soundfx/liboffloadvisualizer.so:system/vendor/lib64/soundfx/liboffloadvisualizer.so

PRODUCT_PACKAGES += \
    libril
#    libhwui

#LOCAL_LDLIBS := -lhwui
